spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

#spring:
#  datasource:
#    url: jdbc:postgresql://junction.proxy.rlwy.net:29053/railway
#    username: postgres
#    password: WhFkKRptLbzJoLjPgRdAASnnBAUCGysi
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

